name: Release
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:17-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y && git --version
#      - run: git config --global --add safe.directory /__w/ConfigIntermediary/ConfigIntermediary
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish --stacktrace -Porg.gradle.parallel.threads=4
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}